//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bibliochat.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("bibliochat.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        internal static string AcceptButtonTitle {
            get {
                return ResourceManager.GetString("AcceptButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elija al usuario cuya solicitud desea aceptar..
        /// </summary>
        internal static string AcceptConnectionRequestsCardInstructions {
            get {
                return ResourceManager.GetString("AcceptConnectionRequestsCardInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar petición.
        /// </summary>
        internal static string AcceptConnectionRequestsCardTitle {
            get {
                return ResourceManager.GetString("AcceptConnectionRequestsCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar o rechazar la solicitud: digite &quot;{0}&quot; para aceptar, &quot;{1}&quot; para rechazar o usar los botones si está habilitado..
        /// </summary>
        internal static string AcceptRejectConnectionHint {
            get {
                return ResourceManager.GetString("AcceptRejectConnectionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para configurar un canal de agregación, escriba &quot;{0}&quot;.
        /// </summary>
        internal static string AddAggregationChannelCommandHint {
            get {
                return ResourceManager.GetString("AddAggregationChannelCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ok ,&quot;{0}&quot; esta listo para recibir solicitudes..
        /// </summary>
        internal static string AggregationChannelAlreadySet {
            get {
                return ResourceManager.GetString("AggregationChannelAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;{}&quot; ya no recibirá solicitudes..
        /// </summary>
        internal static string AggregationChannelRemoved {
            get {
                return ResourceManager.GetString("AggregationChannelRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este canal/conversación es ahora donde se agregan las solicitudes.
        /// </summary>
        internal static string AggregationChannelSet {
            get {
                return ResourceManager.GetString("AggregationChannelSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya está conectado con el usuario &quot;{0}&quot;..
        /// </summary>
        internal static string AlreadyConnectedWithUser {
            get {
                return ResourceManager.GetString("AlreadyConnectedWithUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicar a todo.
        /// </summary>
        internal static string ApplyToAll {
            get {
                return ResourceManager.GetString("ApplyToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bots.
        /// </summary>
        internal static string Bots {
            get {
                return ResourceManager.GetString("Bots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones administrativas para controlar las conversaciones de Bot de usuario final.
        /// </summary>
        internal static string CommandMenuDescription {
            get {
                return ResourceManager.GetString("CommandMenuDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione el comando usando los botones a continuación o escriba la palabra clave de comando (&quot;{0}&quot;)/botle de bot (&quot;@{1}&quot;) seguido del comando y sus parámetros (si los hay), por ejemplo: &quot;{2}&quot; ..
        /// </summary>
        internal static string CommandMenuInstructions {
            get {
                return ResourceManager.GetString("CommandMenuInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comandos.
        /// </summary>
        internal static string CommandMenuTitle {
            get {
                return ResourceManager.GetString("CommandMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comando &quot;{0}&quot; no reconocido..
        /// </summary>
        internal static string CommandNotRecognized {
            get {
                return ResourceManager.GetString("CommandNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se realizó una solicitud de conexión, pero la parte solicitante es nula.
        /// </summary>
        internal static string ConnectionRequestMadeButRequestorIsNull {
            get {
                return ResourceManager.GetString("ConnectionRequestMadeButRequestorIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo siento, no se le permite aceptar ni rechazar solicitudes.
        /// </summary>
        internal static string ConnectionRequestResponseNotAllowed {
            get {
                return ResourceManager.GetString("ConnectionRequestResponseNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error de solicitud de conexión: {0}.
        /// </summary>
        internal static string ConnectionRequestResultErrorWithResult {
            get {
                return ResourceManager.GetString("ConnectionRequestResultErrorWithResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud.
        /// </summary>
        internal static string ConnectionRequestTitle {
            get {
                return ResourceManager.GetString("ConnectionRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error de conexión: {0}.
        /// </summary>
        internal static string ConnectionResultErrorWithResult {
            get {
                return ResourceManager.GetString("ConnectionResultErrorWithResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para iniciar una conversación con un agente, escriba &quot;{0}&quot;.
        /// </summary>
        internal static string ConnectRequestCommandHint {
            get {
                return ResourceManager.GetString("ConnectRequestCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar todos los datos ....
        /// </summary>
        internal static string DeletingAllData {
            get {
                return ResourceManager.GetString("DeletingAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminando todos los datos solicitados por &quot;0&quot;....
        /// </summary>
        internal static string DeletingAllDataWithCommandIssuer {
            get {
                return ResourceManager.GetString("DeletingAllDataWithCommandIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tú dijiste: {0}.
        /// </summary>
        internal static string EchoMessage {
            get {
                return ResourceManager.GetString("EchoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error.
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error: {0}.
        /// </summary>
        internal static string ErrorOccuredWithResult {
            get {
                return ResourceManager.GetString("ErrorOccuredWithResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo encontrar la instancia BOT en el canal de agregación No se pudo encontrar la instancia BOT en el canal de agregación &quot;{0}&quot;.
        /// </summary>
        internal static string FailedToFindBotOnAggregationChannel {
            get {
                return ResourceManager.GetString("FailedToFindBotOnAggregationChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo encontrar la solicitud pendiente.
        /// </summary>
        internal static string FailedToFindPendingRequest {
            get {
                return ResourceManager.GetString("FailedToFindPendingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo encontrar una solicitud pendiente para el usuario &quot;0&quot;: {1}.
        /// </summary>
        internal static string FailedToFindPendingRequestForUserWithErrorMessage {
            get {
                return ResourceManager.GetString("FailedToFindPendingRequestForUserWithErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al reenviar el mensaje.
        /// </summary>
        internal static string FailedToForwardMessage {
            get {
                return ResourceManager.GetString("FailedToForwardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al rechazar solicitudes pendientes.
        /// </summary>
        internal static string FailedToRejectPendingRequests {
            get {
                return ResourceManager.GetString("FailedToRejectPendingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al eliminar el canal de agregación.
        /// </summary>
        internal static string FailedToRemoveAggregationChannel {
            get {
                return ResourceManager.GetString("FailedToRemoveAggregationChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al establecer el canal de agregación: {0}.
        /// </summary>
        internal static string FailedToSetAggregationChannel {
            get {
                return ResourceManager.GetString("FailedToSetAggregationChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comando invalido.
        /// </summary>
        internal static string InvalidCommand {
            get {
                return ResourceManager.GetString("InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetro de comando inválido o faltante.
        /// </summary>
        internal static string InvalidOrMissingCommandParameter {
            get {
                return ResourceManager.GetString("InvalidOrMissingCommandParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos, no hay agentes disponibles en este momento.
        /// </summary>
        internal static string NoAgentsAvailable {
            get {
                return ResourceManager.GetString("NoAgentsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha configurado ningún canal de agregación.
        /// </summary>
        internal static string NoAggregationChannel {
            get {
                return ResourceManager.GetString("NoAggregationChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay bots almacenados.
        /// </summary>
        internal static string NoBotsStored {
            get {
                return ResourceManager.GetString("NoBotsStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin conversaciones.
        /// </summary>
        internal static string NoConversations {
            get {
                return ResourceManager.GetString("NoConversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin solicitudes pendientes.
        /// </summary>
        internal static string NoPendingRequests {
            get {
                return ResourceManager.GetString("NoPendingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay resultados.
        /// </summary>
        internal static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su solicitud fue aceptada y ahora está chateando con {0}.
        /// </summary>
        internal static string NotifyClientConnected {
            get {
                return ResourceManager.GetString("NotifyClientConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu conversación con {0} ha finalizado..
        /// </summary>
        internal static string NotifyClientDisconnected {
            get {
                return ResourceManager.GetString("NotifyClientDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Su solicitud ya ha sido recibida, espere a que un agente responda.
        /// </summary>
        internal static string NotifyClientDuplicateRequest {
            get {
                return ResourceManager.GetString("NotifyClientDuplicateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desafortunadamente su solicitud no pudo ser procesada.
        /// </summary>
        internal static string NotifyClientRequestRejected {
            get {
                return ResourceManager.GetString("NotifyClientRequestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor espere a que su solicitud sea aceptada.
        /// </summary>
        internal static string NotifyClientWaitForRequestHandling {
            get {
                return ResourceManager.GetString("NotifyClientWaitForRequestHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ahora estás conectado al usuario &quot;{0}&quot;.
        /// </summary>
        internal static string NotifyOwnerConnected {
            get {
                return ResourceManager.GetString("NotifyOwnerConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ahora está desconectado de la conversación con el usuario &quot;{0}&quot;.
        /// </summary>
        internal static string NotifyOwnerDisconnected {
            get {
                return ResourceManager.GetString("NotifyOwnerDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud del usuario &quot;{0}&quot; rechazada.
        /// </summary>
        internal static string NotifyOwnerRequestRejected {
            get {
                return ResourceManager.GetString("NotifyOwnerRequestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} no es un canal de agregación permitido.
        /// </summary>
        internal static string NotPermittedAggregationChannel {
            get {
                return ResourceManager.GetString("NotPermittedAggregationChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay usuarios almacenados.
        /// </summary>
        internal static string NoUsersStored {
            get {
                return ResourceManager.GetString("NoUsersStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para ver los comandos disponibles, escriba &quot;{0}&quot;.
        /// </summary>
        internal static string OptionsCommandHint {
            get {
                return ResourceManager.GetString("OptionsCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partido &quot;{0}&quot; eliminado.
        /// </summary>
        internal static string PartyRemoved {
            get {
                return ResourceManager.GetString("PartyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} solicitudes pendientes encontradas.
        /// </summary>
        internal static string PendingRequestsFoundWithCount {
            get {
                return ResourceManager.GetString("PendingRequestsFoundWithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar todo.
        /// </summary>
        internal static string RejectAll {
            get {
                return ResourceManager.GetString("RejectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar.
        /// </summary>
        internal static string RejectButtonTitle {
            get {
                return ResourceManager.GetString("RejectButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar solicitud.
        /// </summary>
        internal static string RejectConnectionRequestCardTitle {
            get {
                return ResourceManager.GetString("RejectConnectionRequestCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elija el usuario cuya solicitud de rechazo..
        /// </summary>
        internal static string RejectConnectionRequestsCardInstructions {
            get {
                return ResourceManager.GetString("RejectConnectionRequestsCardInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot;{0}&quot; en el canal &quot;{1}&quot; ({2}).
        /// </summary>
        internal static string RequestorDetailsItem {
            get {
                return ResourceManager.GetString("RequestorDetailsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se realizó la solicitud, pero faltan los datos del solicitante.
        /// </summary>
        internal static string RequestorDetailsMissing {
            get {
                return ResourceManager.GetString("RequestorDetailsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitado por el usuario &quot;{0}&quot; en el canal &quot;{1}&quot;.
        /// </summary>
        internal static string RequestorDetailsTitle {
            get {
                return ResourceManager.GetString("RequestorDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos del usuario &quot;{0}&quot; eliminados.
        /// </summary>
        internal static string UserDataDeleted {
            get {
                return ResourceManager.GetString("UserDataDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta el nombre de usuario.
        /// </summary>
        internal static string UserNameMissing {
            get {
                return ResourceManager.GetString("UserNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
