//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bibliochat.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("bibliochat.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        internal static string AcceptButtonTitle {
            get {
                return ResourceManager.GetString("AcceptButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elija al usuario cuya solicitud desea aceptar..
        /// </summary>
        internal static string AcceptConnectionRequestsCardInstructions {
            get {
                return ResourceManager.GetString("AcceptConnectionRequestsCardInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar petición.
        /// </summary>
        internal static string AcceptConnectionRequestsCardTitle {
            get {
                return ResourceManager.GetString("AcceptConnectionRequestsCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar o rechazar la solicitud: digite &quot;{0}&quot; para aceptar, &quot;{1}&quot; para rechazar o usar los botones si está habilitado..
        /// </summary>
        internal static string AcceptRejectConnectionHint {
            get {
                return ResourceManager.GetString("AcceptRejectConnectionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para configurar un canal de agregación, escriba &quot;{0}&quot;.
        /// </summary>
        internal static string AddAggregationChannelCommandHint {
            get {
                return ResourceManager.GetString("AddAggregationChannelCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok ,&quot;{0}&quot; esta listo para recibir solicitudes..
        /// </summary>
        internal static string AggregationChannelAlreadySet {
            get {
                return ResourceManager.GetString("AggregationChannelAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{}&quot; ya no recibirá solicitudes..
        /// </summary>
        internal static string AggregationChannelRemoved {
            get {
                return ResourceManager.GetString("AggregationChannelRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este canal/conversación es ahora donde se agregan las solicitudes.
        /// </summary>
        internal static string AggregationChannelSet {
            get {
                return ResourceManager.GetString("AggregationChannelSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya está conectado con el usuario &quot;{0}&quot;..
        /// </summary>
        internal static string AlreadyConnectedWithUser {
            get {
                return ResourceManager.GetString("AlreadyConnectedWithUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar a todo.
        /// </summary>
        internal static string ApplyToAll {
            get {
                return ResourceManager.GetString("ApplyToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bots.
        /// </summary>
        internal static string Bots {
            get {
                return ResourceManager.GetString("Bots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opciones administrativas para controlar las conversaciones de Bot de usuario final.
        /// </summary>
        internal static string CommandMenuDescription {
            get {
                return ResourceManager.GetString("CommandMenuDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el comando usando los botones a continuación o escriba la palabra clave de comando (&quot;{0}&quot;)/botle de bot (&quot;@{1}&quot;) seguido del comando y sus parámetros (si los hay), por ejemplo: &quot;{2}&quot; ..
        /// </summary>
        internal static string CommandMenuInstructions {
            get {
                return ResourceManager.GetString("CommandMenuInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comandos.
        /// </summary>
        internal static string CommandMenuTitle {
            get {
                return ResourceManager.GetString("CommandMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando &quot;{0}&quot; no reconocido..
        /// </summary>
        internal static string CommandNotRecognized {
            get {
                return ResourceManager.GetString("CommandNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se realizó una solicitud de conexión, pero la parte solicitante es nula.
        /// </summary>
        internal static string ConnectionRequestMadeButRequestorIsNull {
            get {
                return ResourceManager.GetString("ConnectionRequestMadeButRequestorIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo siento, no se le permite aceptar ni rechazar solicitudes.
        /// </summary>
        internal static string ConnectionRequestResponseNotAllowed {
            get {
                return ResourceManager.GetString("ConnectionRequestResponseNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error de solicitud de conexión: {0}.
        /// </summary>
        internal static string ConnectionRequestResultErrorWithResult {
            get {
                return ResourceManager.GetString("ConnectionRequestResultErrorWithResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud.
        /// </summary>
        internal static string ConnectionRequestTitle {
            get {
                return ResourceManager.GetString("ConnectionRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error de conexión: {0}.
        /// </summary>
        internal static string ConnectionResultErrorWithResult {
            get {
                return ResourceManager.GetString("ConnectionResultErrorWithResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para iniciar una conversación con un agente, escriba &quot;{0}&quot;.
        /// </summary>
        internal static string ConnectRequestCommandHint {
            get {
                return ResourceManager.GetString("ConnectRequestCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar todos los datos ....
        /// </summary>
        internal static string DeletingAllData {
            get {
                return ResourceManager.GetString("DeletingAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminando todos los datos solicitados por &quot;0&quot;....
        /// </summary>
        internal static string DeletingAllDataWithCommandIssuer {
            get {
                return ResourceManager.GetString("DeletingAllDataWithCommandIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tú dijiste: {0}.
        /// </summary>
        internal static string EchoMessage {
            get {
                return ResourceManager.GetString("EchoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error.
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se produjo un error: {0}.
        /// </summary>
        internal static string ErrorOccuredWithResult {
            get {
                return ResourceManager.GetString("ErrorOccuredWithResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo encontrar la instancia BOT en el canal de agregación No se pudo encontrar la instancia BOT en el canal de agregación &quot;{0}&quot;.
        /// </summary>
        internal static string FailedToFindBotOnAggregationChannel {
            get {
                return ResourceManager.GetString("FailedToFindBotOnAggregationChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo encontrar la solicitud pendiente.
        /// </summary>
        internal static string FailedToFindPendingRequest {
            get {
                return ResourceManager.GetString("FailedToFindPendingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo encontrar una solicitud pendiente para el usuario &quot;0&quot;: {1}.
        /// </summary>
        internal static string FailedToFindPendingRequestForUserWithErrorMessage {
            get {
                return ResourceManager.GetString("FailedToFindPendingRequestForUserWithErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al reenviar el mensaje.
        /// </summary>
        internal static string FailedToForwardMessage {
            get {
                return ResourceManager.GetString("FailedToForwardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al rechazar solicitudes pendientes.
        /// </summary>
        internal static string FailedToRejectPendingRequests {
            get {
                return ResourceManager.GetString("FailedToRejectPendingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al eliminar el canal de agregación.
        /// </summary>
        internal static string FailedToRemoveAggregationChannel {
            get {
                return ResourceManager.GetString("FailedToRemoveAggregationChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al establecer el canal de agregación: {0}.
        /// </summary>
        internal static string FailedToSetAggregationChannel {
            get {
                return ResourceManager.GetString("FailedToSetAggregationChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando invalido.
        /// </summary>
        internal static string InvalidCommand {
            get {
                return ResourceManager.GetString("InvalidCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parámetro de comando inválido o faltante.
        /// </summary>
        internal static string InvalidOrMissingCommandParameter {
            get {
                return ResourceManager.GetString("InvalidOrMissingCommandParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo sentimos, no hay agentes disponibles en este momento.
        /// </summary>
        internal static string NoAgentsAvailable {
            get {
                return ResourceManager.GetString("NoAgentsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha configurado ningún canal de agregación.
        /// </summary>
        internal static string NoAggregationChannel {
            get {
                return ResourceManager.GetString("NoAggregationChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay bots almacenados.
        /// </summary>
        internal static string NoBotsStored {
            get {
                return ResourceManager.GetString("NoBotsStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin conversaciones.
        /// </summary>
        internal static string NoConversations {
            get {
                return ResourceManager.GetString("NoConversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin solicitudes pendientes.
        /// </summary>
        internal static string NoPendingRequests {
            get {
                return ResourceManager.GetString("NoPendingRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay resultados.
        /// </summary>
        internal static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su solicitud fue aceptada y ahora está chateando con {0}.
        /// </summary>
        internal static string NotifyClientConnected {
            get {
                return ResourceManager.GetString("NotifyClientConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu conversación con {0} ha finalizado..
        /// </summary>
        internal static string NotifyClientDisconnected {
            get {
                return ResourceManager.GetString("NotifyClientDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su solicitud ya ha sido recibida, espere a que un agente responda.
        /// </summary>
        internal static string NotifyClientDuplicateRequest {
            get {
                return ResourceManager.GetString("NotifyClientDuplicateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desafortunadamente su solicitud no pudo ser procesada.
        /// </summary>
        internal static string NotifyClientRequestRejected {
            get {
                return ResourceManager.GetString("NotifyClientRequestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor espere a que su solicitud sea aceptada.
        /// </summary>
        internal static string NotifyClientWaitForRequestHandling {
            get {
                return ResourceManager.GetString("NotifyClientWaitForRequestHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahora estás conectado al usuario &quot;{0}&quot;.
        /// </summary>
        internal static string NotifyOwnerConnected {
            get {
                return ResourceManager.GetString("NotifyOwnerConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ahora está desconectado de la conversación con el usuario &quot;{0}&quot;.
        /// </summary>
        internal static string NotifyOwnerDisconnected {
            get {
                return ResourceManager.GetString("NotifyOwnerDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud del usuario &quot;{0}&quot; rechazada.
        /// </summary>
        internal static string NotifyOwnerRequestRejected {
            get {
                return ResourceManager.GetString("NotifyOwnerRequestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} no es un canal de agregación permitido.
        /// </summary>
        internal static string NotPermittedAggregationChannel {
            get {
                return ResourceManager.GetString("NotPermittedAggregationChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hay usuarios almacenados.
        /// </summary>
        internal static string NoUsersStored {
            get {
                return ResourceManager.GetString("NoUsersStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para ver los comandos disponibles, escriba &quot;{0}&quot;.
        /// </summary>
        internal static string OptionsCommandHint {
            get {
                return ResourceManager.GetString("OptionsCommandHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partido &quot;{0}&quot; eliminado.
        /// </summary>
        internal static string PartyRemoved {
            get {
                return ResourceManager.GetString("PartyRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} solicitudes pendientes encontradas.
        /// </summary>
        internal static string PendingRequestsFoundWithCount {
            get {
                return ResourceManager.GetString("PendingRequestsFoundWithCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazar todo.
        /// </summary>
        internal static string RejectAll {
            get {
                return ResourceManager.GetString("RejectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazar.
        /// </summary>
        internal static string RejectButtonTitle {
            get {
                return ResourceManager.GetString("RejectButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechazar solicitud.
        /// </summary>
        internal static string RejectConnectionRequestCardTitle {
            get {
                return ResourceManager.GetString("RejectConnectionRequestCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elija el usuario cuya solicitud de rechazo..
        /// </summary>
        internal static string RejectConnectionRequestsCardInstructions {
            get {
                return ResourceManager.GetString("RejectConnectionRequestsCardInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; en el canal &quot;{1}&quot; ({2}).
        /// </summary>
        internal static string RequestorDetailsItem {
            get {
                return ResourceManager.GetString("RequestorDetailsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se realizó la solicitud, pero faltan los datos del solicitante.
        /// </summary>
        internal static string RequestorDetailsMissing {
            get {
                return ResourceManager.GetString("RequestorDetailsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitado por:-{0}.
        /// </summary>
        internal static string RequestorDetailsTitle {
            get {
                return ResourceManager.GetString("RequestorDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos del usuario &quot;{0}&quot; eliminados.
        /// </summary>
        internal static string UserDataDeleted {
            get {
                return ResourceManager.GetString("UserDataDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falta el nombre de usuario.
        /// </summary>
        internal static string UserNameMissing {
            get {
                return ResourceManager.GetString("UserNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
